INSERT INTO regiones (nombre) VALUES('Suramerica');
INSERT INTO regiones (nombre) VALUES('Centroamerica');
INSERT INTO regiones (nombre) VALUES('Norteamerica');
INSERT INTO regiones (nombre) VALUES('Europa');
INSERT INTO regiones (nombre) VALUES('Asia');
INSERT INTO regiones (nombre) VALUES('Africa');
INSERT INTO regiones (nombre) VALUES('Oceania');
INSERT INTO regiones (nombre) VALUES('Antartida');

INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 1,'Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 2,'Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 3,'Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 4,'Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 5,'Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 6,'Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 7,'Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 8,'John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 1,'Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 2,'Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 3,'Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 4,'Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 5,'Andrés', 'Guzmán', 'profesor1@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 6,'Mr. John', 'Doe', 'john.doe1@gmail.com', '2018-01-02');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 7,'Linus', 'Torvalds', 'linus.torvalds1@gmail.com', '2018-01-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 8,'Rasmus', 'Lerdorf', 'rasmus.lerdorf1@gmail.com', '2018-01-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 1,'Erich', 'Gamma', 'erich.gamma1@gmail.com', '2018-02-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 2,'Richard', 'Helm', 'richard.helm1@gmail.com', '2018-02-10');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 3,'Ralph', 'Johnson', 'ralph.johnson1@gmail.com', '2018-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 4,'John', 'Vlissides', 'john.vlissides1@gmail.com', '2018-02-28');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 5,'Dr. James', 'Gosling', 'james.gosling1@gmail.com', '2018-03-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 6,'Magma', 'Lee', 'magma.lee1@gmail.com', '2018-03-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 7,'Tornado', 'Roe', 'tornado.roe1@gmail.com', '2018-03-05');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 8,'Jade', 'Doe', 'jane.doe1@gmail.com', '2018-03-06');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 1,'Andrés', 'Guzmán', 'profesor2@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 2,'Mr. John', 'Doe', 'john.doe2@gmail.com', '2018-01-02');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 3,'Linus', 'Torvalds', 'linus.torvalds2@gmail.com', '2018-01-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 4,'Rasmus', 'Lerdorf', 'rasmus.lerdorf2@gmail.com', '2018-01-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 5,'Erich', 'Gamma', 'erich.gamma2@gmail.com', '2018-02-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 6,'Richard', 'Helm', 'richard.helm2@gmail.com', '2018-02-10');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 7,'Ralph', 'Johnson', 'ralph.johnson2@gmail.com', '2018-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 8,'John', 'Vlissides', 'john.vlissides2@gmail.com', '2018-02-28');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 1,'Dr. James', 'Gosling', 'james.gosling2@gmail.com', '2018-03-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 2,'Magma', 'Lee', 'magma.lee2@gmail.com', '2018-03-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 3,'Tornado', 'Roe', 'tornado.roe2@gmail.com', '2018-03-05');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 4,'Jade', 'Doe', 'jane.doe2@gmail.com', '2018-03-06');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 5,'Andrés', 'Guzmán', 'profesor3@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 6,'Mr. John', 'Doe', 'john.doe3@gmail.com', '2018-01-02');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 7,'Linus', 'Torvalds', 'linus.torvalds3@gmail.com', '2018-01-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 8,'Rasmus', 'Lerdorf', 'rasmus.lerdorf3@gmail.com', '2018-01-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 1,'Erich', 'Gamma', 'erich.gamma3@gmail.com', '2018-02-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 2,'Richard', 'Helm', 'richard.helm3@gmail.com', '2018-02-10');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 3,'Ralph', 'Johnson', 'ralph.johnson3@gmail.com', '2018-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 4,'John', 'Vlissides', 'john.vlisside3@gmail.com', '2018-02-28');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 5,'Dr. James', 'Gosling', 'james.gosling3@gmail.com', '2018-03-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 6,'Magma', 'Lee', 'magma.lee3@gmail.com', '2018-03-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 7,'Tornado', 'Roe', 'tornado.roe3@gmail.com', '2018-03-05');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 8,'Jade', 'Doe', 'jane.doe3@gmail.com', '2018-03-06');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 1,'Andrés', 'Guzmán', 'profesor4@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 2,'Mr. John', 'Doe', 'john.doe4@gmail.com', '2018-01-02');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 3,'Linus', 'Torvalds', 'linus.torvalds4@gmail.com', '2018-01-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 4,'Rasmus', 'Lerdorf', 'rasmus.lerdorf4@gmail.com', '2018-01-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 5,'Erich', 'Gamma', 'erich.gamma4@gmail.com', '2018-02-01');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 6,'Richard', 'Helm', 'richard.helm4@gmail.com', '2018-02-10');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 7,'Ralph', 'Johnson', 'ralph.johnson4@gmail.com', '2018-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 8,'John', 'Vlissides', 'john.vlisside4@gmail.com', '2018-02-28');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 1,'Dr. James', 'Gosling', 'james.gosling4@gmail.com', '2018-03-03');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 2,'Magma', 'Lee', 'magma.lee4@gmail.com', '2018-03-04');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 3,'Tornado', 'Roe', 'tornado.roe4@gmail.com', '2018-03-05');
INSERT INTO clientes (region_id, nombre, apellido, email, fecha_creacion) VALUES( 4,'Jade', 'Doe', 'jane.doe4@gmail.com', '2018-03-06');